- name: install catalogue component
  hosts: catalogue
  become: 'yes'
  tasks:
    - name: Setup NodeJS repos
      ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

    - name: Install NodeJS
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: Check if roboshop user exists or not using id
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - when: out.rc == 0
      name: Create roboshop user if not exists
      become: 'yes'
      ansible.builtin.user:
        name: roboshop

    - name: Check if /app directory exists or not
      ansible.builtin.stat:
        path: /app
        register: directory

    - name: print directory status
      ansible.builtin.debug:
        msg: 'output: {{directory}}'

    - when: directory stat.exists == False
      name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: Extract catalogue artifact
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: 'yes'

    - name: download the dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Copy file catalogue.service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Copy file mongo.repo to yum.repos.d
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb-org-shell
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: load catalogue data
      ansible.builtin.command: mongo --host MONGODB-SERVER-IPADDRESS < /app/schema/catalogue.js
    
    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: 'yes'
